language: node_js

node_js:
   - "v10.23.0" # will use latest node

addons:
  apt:
    packages:
    - sshpass
  #chrome: stable # have Travis install chrome stable.

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli@1.7.4

script: # the build step
    - ng build --aot --prod --build-optimizer
    - ng test --single-run

deploy:
  #deploy to production
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh production
    skip_cleanup: true
    on:
     branch: master
  #deploy to staging
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/travis-webfaction-deploy.sh staging
    skip_cleanup: true
    on:
      branch: staging
